services:
  postgres:
    image: postgres:14
    container_name: monprojet-postgres14
    environment:
      POSTGRES_DB: roadworks
      POSTGRES_USER: roadworks
      POSTGRES_PASSWORD: roadworks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/reset-database.sql:/docker-entrypoint-initdb.d/01-create.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadworks -d roadworks"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: maven:3.9.5-eclipse-temurin-17
    container_name: monprojet-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - m2cache:/root/.m2
      - backend_target:/app/target
      - ./backend/firebase-key.json:/app/firebase-key.json:ro
    ports:
      - "8080:8080"
    command: sh -c "mvn -DskipTests package && java -jar target/*.jar"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75 -Djava.security.egd=file:/dev/./urandom"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/roadworks
      SPRING_DATASOURCE_USERNAME: roadworks
      SPRING_DATASOURCE_PASSWORD: roadworks
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FIREBASE_CREDENTIALS_PATH: /app/firebase-key.json
    depends_on:
      postgres:
        condition: service_healthy

  frontoffice:
    image: node:22.19.0-alpine
    container_name: monprojet-frontoffice
    working_dir: /app
    volumes:
      - ./web/frontoffice:/app
      - frontoffice_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "if [ ! -f node_modules/.bin/vite ]; then npm ci; fi && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  backoffice:
    image: node:22.19.0-alpine
    container_name: monprojet-backoffice
    working_dir: /app
    volumes:
      - ./web/backoffice:/app
      - backoffice_node_modules:/app/node_modules
    ports:
      - "5174:5173"
    command: sh -c "if [ ! -f node_modules/.bin/vite ]; then npm ci; fi && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  map:
    image: maptiler/tileserver-gl:latest
    container_name: roadworks-tileserver
    ports:
      - "8089:8080"
    volumes:
      - ./maps/data:/data
    command: ["--mbtiles", "/data/antananarivo.mbtiles"]

volumes:
  pgdata:
  backend_target:
  frontoffice_node_modules:
  backoffice_node_modules:
  m2cache:
