services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: monprojet-postgres14
    environment:
      POSTGRES_DB: roadworks
      POSTGRES_USER: roadworks
      POSTGRES_PASSWORD: roadworks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadworks -d roadworks"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: maven:3.9.5-eclipse-temurin-17
    container_name: monprojet-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: sh -c "mvn spring-boot:run"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/roadworks
      SPRING_DATASOURCE_USERNAME: roadworks
      SPRING_DATASOURCE_PASSWORD: roadworks
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

  frontoffice:
    image: node:22.19.0-alpine
    container_name: monprojet-frontoffice
    working_dir: /app
    volumes:
      - ./web/frontoffice:/app
      - ./web/frontoffice/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  backoffice:
    image: node:22.19.0-alpine
    container_name: monprojet-backoffice
    working_dir: /app
    volumes:
      - ./web/backoffice:/app
      - ./web/backoffice/node_modules:/app/node_modules
    ports:
      - "5174:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  map:
    image: maptiler/tileserver-gl:latest
    container_name: roadworks-tileserver
    ports:
      - "8081:8080"
    volumes:
      - ./maps/data:/data
    command: ["--mbtiles", "/data/antananarivo.mbtiles"]

volumes:
  pgdata:
